project:
  type: website
  output-dir: docs

website:
  title: "AI for Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mlori77
      
format:
  html:
    theme: theme.scss
    #theme: cosmo
    #css: styles.css

editor: visual

