project:
  type: website

website:
  title: "Machine Learning Blog - Mohammad Shamsodini Lori"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mlori77
      
format:
  html:
    theme: theme.scss
    #theme: cosmo
    #css: styles.css

editor: visual

